export const REQUEST_GET_POST_TYPES                   = "REQUEST_GET_POST_TYPES"
export const REQUEST_GET_POST_TYPES_SUCCESS           = "REQUEST_GET_POST_TYPES_SUCCESS"

export const REQUEST_GET_POSTS                        = "REQUEST_GET_POSTS"
export const REQUEST_GET_POSTS_SUCCESS                = "REQUEST_GET_POSTS_SUCCESS"

export const REQUEST_GET_POST                        = "REQUEST_GET_POST"
export const REQUEST_GET_POST_SUCCESS                = "REQUEST_GET_POST_SUCCESS"

export const REQUEST_GET_POST_TO_WP_POST             = "REQUEST_GET_POST_TO_WP_POST"
export const REQUEST_GET_POST_TO_WP_POST_SUCCESS     = "REQUEST_GET_POST_TO_WP_POST_SUCCESS"

export const REQUEST_IMPORT_POSTS_WP             = "REQUEST_IMPORT_POSTS_WP"
export const REQUEST_IMPORT_POSTS_WP_SUCCESS     = "REQUEST_IMPORT_POSTS_WP_SUCCESS"

